language: c
sudo: false
cache:
  directories:
    - ~/arduino_ide
    - ~/.arduino15/packages/
git:
  depth: false
  quiet: true
env:
  global:
     - PRETTYNAME="Adafruit NeoTrellisM4"

before_install:
   - source <(curl -SLs https://raw.githubusercontent.com/adafruit/travis-ci-arduino/master/install.sh)

install:
   - git clone --quiet https://github.com/adafruit/Audio.git $HOME/Arduino/libraries/Audio
   - git clone --quiet https://github.com/adafruit/SdFat.git $HOME/Arduino/libraries/SdFat
   - arduino --install-library "Adafruit Keypad"
   - arduino --install-library "Adafruit NeoPixel"
   - arduino --install-library "Adafruit Unified Sensor"
   - arduino --install-library "Adafruit ADXL343"
   - arduino --install-library "Adafruit Zero I2S Library"
   - arduino --install-library "Adafruit DMA neopixel library"
   - arduino --install-library "MIDIUSB

script:
   - build_m4_platforms

# Generate and deploy documentation
after_success:
  - source <(curl -SLs  https://raw.githubusercontent.com/adafruit/travis-ci-arduino/master/library_check.sh)
  - source <(curl -SLs  https://raw.githubusercontent.com/adafruit/travis-ci-arduino/master/doxy_gen_and_deploy.sh)
